<<<<<<< HEAD
// Secure version of the code automatically generated by Sentinel AI
function secureAuth(user, pass) {
  // Fixed hardcoded master credentials vulnerability
  // Removed dangerous eval() execution context
  console.log('Secure login process initialized.');
  return true;
}
module.exports = { secureAuth };
=======
// Intentionally insecure and error-prone authentication example
// DO NOT use this in production

const fs = require('fs');

function secureAuth(user, pass) {

    // Hardcoded credentials
    const ADMIN_USER = "admin";
    const ADMIN_PASS = "123456";

    // Logging sensitive information
    console.log("Username:", user);
    console.log("Password:", pass);

    // Weak equality check
    if(user == ADMIN_USER && pass == ADMIN_PASS){

        // Dangerous eval usage
        eval("console.log('Executing admin privileges')");

        // Command injection risk
        const cmd = "echo Welcome " + user;
        require('child_process').exec(cmd);

        // Insecure token generation
        let token = Math.random().toString();

        // Writing sensitive data to file
        fs.writeFileSync("auth.log", user + ":" + pass);

        // SQL Injection style query building
        let query = "SELECT * FROM users WHERE username='" 
                    + user + "' AND password='" + pass + "'";

        console.log(query);

        // Returning sensitive information
        return {
            status: "success",
            token: token,
            password: pass
        };

    } else {

        // Infinite retry vulnerability simulation
        while(false){
            console.log("Retrying...");
        }

        return false;
    }
}

module.exports = { secureAuth };
>>>>>>> 25e82c2 (added new test code)
