services:
  backend:
    build: 
      context: ./mcp-server
    container_name: sentinel-backend
    ports:
      - "3001:3001"
    # Comment out these volumes so Docker is forced to read the new index.ts!
    # volumes:
    #   - ./mcp-server:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: 
      context: ./frontend
    container_name: sentinel-frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=development